name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    env:
      CI: ""

    steps:
    - uses: actions/checkout@v2
  
    - uses: Azure/docker-login@v1
      with:
        login-server: tailwindtradersado40.azurecr.io
        username: tailwindtradersado40
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        cd Source/Tailwind.Traders.Web
        docker build . -t tailwindtradersado40.azurecr.io/tailwindtraders-ado40:${{ github.sha }} -t tailwindtradersado40.azurecr.io/tailwindtraders-ado40:latest
        docker push tailwindtradersado40.azurecr.io/tailwindtraders-ado40:${{ github.sha }}
        cd ..