name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: TailwindTraders-ADO40

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Install dependencies
      run: dotnet restore ./Source/*.sln
    
    - name: Build
      run: dotnet build ./Source/*.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./Source/*.sln --no-restore --verbosity normal
    
    - name: Publish
      run:  dotnet publish ./Source/Tailwind.Traders.Web/Tailwind.Traders.Web.csproj -c Release -o './staging'
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: './Source/Tailwind.Traders.Web/staging'
    
    - name: Deploy to Website
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
        package: './Source/Tailwind.Traders.Web/staging'

    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
        title: 'PR Deployment Completed - ${{ env.GITHUB_RUN_ID }}'
        summary: '.NET Core PR deployment has succeeded Run ID: ${{ env.GITHUB_RUN_ID }}'
        text: '*ALL THE VARIABLES!* [${{ github.event.compare }}]'
        theme_color: '222222'
        sections: '[{"activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png","activityTitle": "PR Build completed: [${{ github.event.pull_request.url }}](${{ github.event.pull_request.url }})","activityText": "Commit message: [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url }})"}]'
        actions: '[{"@type": "OpenUri","name": "Open Staging Site","targets": [{"os": "default","uri": "${{ github.event.head_commit.url }}"}]},{"@type": "OpenUri","name": "Promote to Production","targets": [{"os": "default","uri": "${{ github.event.head_commit.url }}"}]}]'