name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: TailwindTraders-ADO40

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Install dependencies
      run: dotnet restore ./Source/*.sln
    
    - name: Build
      run: dotnet build ./Source/*.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./Source/*.sln --no-restore --verbosity normal
    
    - name: Publish
      run:  dotnet publish ./Source/Tailwind.Traders.Web/Tailwind.Traders.Web.csproj -c Release -o ~/drop
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ~/drop
    
    - name: Deploy to Website
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
        package: ~/drop/**.*
