name: .NET Core

on:
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: TailwindTraders-ADO40-PR

jobs:
  build:

    runs-on: ubuntu-18.04
    env:
      CI: ""
      baseRunUrl: "https://github.com/Damovisa/TailwindTraders-ADO40/actions/runs/"

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
   
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
   
    - name: Install dependencies
      run: dotnet restore ./Source/*.sln
   
    - name: Build
      run: dotnet build ./Source/*.sln --configuration Release --no-restore
   
    - name: Test
      run: dotnet test ./Source/*.sln --no-restore --verbosity normal
   
    - name: Publish
      run: dotnet publish ./Source/Tailwind.Traders.Web/Tailwind.Traders.Web.csproj -c Release -o './staging'
   
    - name: Deploy to Website
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PR }}
        package: './Source/Tailwind.Traders.Web/staging'